import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin, AiFillFacebook} from "react-icons/ai";
import {SiLeetcode} from "react-icons/si";
import Image from 'next/image';
import sspp from '../public/sspp.png';
import { useState } from 'react';
import {Ubuntu} from '@next/font/google';

const ubuntu = Ubuntu({
  subsets:['latin'],
  weight: ['300','400'],
});

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Suraj Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=' min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between'>
          <div className='text-xl'>
            <a href='https://www.shahneha.com.np'><h1 className={ubuntu.className}>developedby</h1></a>
          </div>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer text-2xl'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="http://www.surajsharma1.com.np/Resume.pdf" download>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-2'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Suraj Sharma</h2>
           <h3 className='text-2xl py-2 md:text-3xl'>Software Engineer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto'>
              Freelancer providing services for programming needs. If you are looking for someone to handle the technical aspects of your web or desktop app, a skilled backend developer can help you build a robust and reliable backend system that supports your business needs.
            </p>
          </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <a href='https://leetcode.com/surajaskmini/?fbclid=IwAR0CgusBUkUx3oFJD4IynrZSoV8m5F40nnoLyu4qmCFv0C82QS7CgJZ4EjQ'><SiLeetcode/></a>  
              <a href='https://www.linkedin.com/in/suraj-sharma-a049a31a8/'><AiFillLinkedin/></a>
              <a href='https://github.com/S8r2j'><AiFillGithub/></a>
              <a href='https://www.facebook.com/profile.php?id=100039008803650'><AiFillFacebook /></a>      
            </div>
          <div className='relative flex justify-center mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={sspp}/>
          </div>
        </section>
        <section>
          <div>
            <h2 className='text-3xl py-1'>My Projects</h2>
            <a href='https://github.com/S8r2j/PDF_Rotate_API'>
               <button className=' bg-cyan-500 text-white py-4 w-3/4 lg:w-1/6 ml-10 rounded-full m-3 hover:bg-teal-500'>PDF_Rotate_API</button>
            </a>
            <a href='https://github.com/S8r2j/SuperMarketSystem'>
               <button className=' bg-cyan-400 text-white py-4 w-3/4 lg:w-1/4 ml-10 lg:ml-3 rounded-full m-3  hover:bg-teal-500'>Super_Market_System</button>
            </a>
            <a href='https://github.com/S8r2j/Library_Management_System'>
               <button className=' bg-teal-400 text-white py-4 w-3/4 lg:w-1/4 ml-10 lg:ml-3 rounded-full m-3 hover:bg-teal-500'>Library_Management_System</button>
            </a>
            <a href='https://github.com/S8r2j/Notepad_project'>
               <button className=' bg-teal-500 text-white py-4 w-3/4 lg:w-1/6 ml-10 lg:ml-3 rounded-full m-3 hover:bg-teal-600'>Notepad_project</button>
            </a>
          </div>
        </section>
        <footer class="bg-gradient-to-r from-cyan-500 to-teal-500 m-5 mr-7 px-4 rounded-md ml-8 py-12">
          <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="lg:flex lg:justify-between">
              <div class="w-full lg:w-1/2 mb-8 lg:mb-0">
                <h2 class="text-2xl text-center pb-4 text-white mb-4">Contact Us</h2>
                <form>
                  <div class="mb-4">
                    <input class="appearance-none border rounded-full w-full py-2 px-3 text-gray-300 leading-tight focus:outline-none focus:shadow-outline" id="name" type="text" placeholder="Name"/>
                  </div>
                  <div class="mb-4">
                    <input class="appearance-none border rounded-full w-full py-2 px-3 text-gray-300 leading-tight focus:outline-none focus:shadow-outline" id="email" type="email" placeholder="Email"/>
                  </div>
                  <div class="mb-6">
                    <textarea class="appearance-none border rounded-md w-full py-2 px-3 text-gray-300 leading-tight focus:outline-none focus:shadow-outline" id="message" placeholder="Enter your message here"></textarea>
                  </div>
                  <div class="flex items-center justify-center">
                    <button class="bg-teal-700 hover:bg-teal-600 text-white  py-2 px-6 rounded-md focus:outline-none focus:shadow-outline" type="button">
                      Submit
                    </button>
                  </div>
                </form>
              </div>
              <div class="w-full lg:w-1/2 mt-1 lg:mt-24">
                <div class="pb-5 lg:justify-end">
                  <p class="text-gray-200 hover:text-gray-100 text-2xl  text-center mr-4">
                    <i class="fab fa-twitter fa-2x">Suraj Sharma</i>
                  </p>
                  <p class="text-gray-200 text-center text-2xl hover:text-gray-100">
                    <i class="fab fa-instagram fa-2x">surajaskmini@gmail.com</i>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </main>
    </div>
  </>
  )
}
